#!env/bin/python
# push to api.the-huck.com
# if project doesn't exist: create and push all commits in bulk
# else: push commits involved in current push only

import requests, json, os, string, sys, git
from requests.auth import HTTPBasicAuth
from datetime import datetime

def prompt(s):
  print s
  return sys.stdin.readline().strip()

API = '127.0.0.1:5000' # dev
#API = 'api.the-huck.com' # prod
gitprojects = 'http://%s/gitprojects' % API
gitcommits = 'http://%s/gitcommits' % API

# project name & url
project_dir = os.path.dirname(os.path.abspath(__file__))
patharr = string.split(project_dir, '/')
project = patharr[-1]
if os.path.join(*patharr[-2:]) == '.git/hooks':
  project = patharr[-3]
  project_dir = os.path.join(*patharr[:-2])
project_url = '%s/%s' % (gitprojects, project)
print project_url

# check whether project exists, add if not
if requests.get(project_url).status_code != requests.codes.ok:
  print 'adding %s' % project
  r = requests.post(
    gitprojects, data={'name': project},
    auth=HTTPBasicAuth(prompt('API user: '), prompt('password: '))
  )
  r.raise_for_status()
else:
  print '%s already exists. ok.' % project

# get the project id
project_id = requests.get(project_url).json().get('_id')

# get the payload of commits
# TODO: other than master branch? '--all'
# TODO: get pushing author and select commits. '--author=Patrick' c.author
# TODO: datetime.datetime '--date=local'
# TODO: if repo existed: repo.iter_commits('github/master..HEAD') -> remote name?
repo = git.Repo(project_dir)
payload = [
  {
    'project': project_id, 'message': c.summary,
    'datetime': datetime.fromtimestamp(c.committed_date).strftime('%c')
  }
  for c in repo.iter_commits()
]
print payload[0]

# push payload to API
headers = {'content-type': 'application/json'}
requests.post(
  gitcommits, data=json.dumps(payload), headers=headers,
  auth=HTTPBasicAuth(prompt('API user: '), prompt('password: '))
)
